
export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About RedhatCoin',
    // headline: 'Unlimited Transactions with zero fees',
    description: 'RedhatCoin aims to make decentralized finance completely secure and to provide the most secure payment system to multinational companies and organizations including investors, around the world, allowing them to easily and securely transact digital transactions using blockchain technology and be able to own their valuable assets RedhatCoin is a fully Decentralized Cryptocurrency based on the goal that it will be the safest global Digital Currency in the world and will be used worldwide as a payment method.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: 'images/redhat.png',
    alt: 'Redhat',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: 'images/svg-2.svg',
    alt: 'Piggybank',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team',
    headline: 'Creating an account is extremely easy',
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you're ready to go.",
    buttonLabel: 'Start Now',
    imgStart: false,
    img: 'images/svg-3.svg',
    alt: 'Paper',
    dark: false,
    primary: false,
    darkText: true,
}